version: '3'
services:
  naxum:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: naxum
    ports:
      - 8052:8052
    volumes:
      - .:/var/www
    links:
      - mysql
    entrypoint: sh -c "cd /var/www/
        && composer install --working-dir=/var/www
        && php artisan migrate
        && php artisan db:seed
        && php artisan serve --host 0.0.0.0 --port=8052"
    environment:
      DB_HOST: mysql
      DB_DATABASE: naxum
      DB_USERNAME: root
      DB_PASSWORD: password
    depends_on:
      - mysql

  mysql:
    image: mysql:5.6
    container_name: mysql_naxum
    ports:
      - 3306
    environment:
      MYSQL_DATABASE: naxum
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - TESTSUITE_PASSWORD=password
      - PMA_HOSTS=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions
    links:
      - mysql
    depends_on:
      - mysql
